### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by joeschmoe1869** [vladimiry/ElectronMail#243]
Does Electron Mail support 2 factor authentication? If so, how do I input the 6 digit code?

**Comment by BBaoVanC** [comment]
When you set up 2FA, there's a code which is a translation of the QR Code. If you add that to your account in ElectronMail, then it will automatically generate the 6 digit code and enter it.

**Comment by joeschmoe1869** [comment]
I can log in via Protonmails web interface. I'm using 1Password on a Mac as my authenticator 

I did configure the 2FA in Electron Mail. But when I try to log in via Electron mail all I see is the password field. No field for the 6 digit number

**Comment by BBaoVanC** [comment]
Is ElectronMail automatically entering the email and password? For me, it automatically enters them which then takes it to the next page where it enters my 2FA code.
So: email & password > 2fa > logged in

**Comment by joeschmoe1869** [comment]
No, it presents the password field. I enter the password and then get the error message unable to decrypt

**Comment by BBaoVanC** [comment]
What happens if you delete the account from ElectronMail and then readd it back?

**Comment by vladimiry** [comment]
> Does Electron Mail support 2 factor authentication? If so, how do I input the 6 digit code?

The app supports automatic generating and filling 2FA tokens. See this issue https://github.com/vladimiry/ElectronMail/issues/10 for details. So you enter in the app settings secret seed, not the one-time-token 6 digits token. So 6 digits token supposed to be filled on the proton form, but not in the app settings.

If you don't want to save the credentials in the app but still want automated login, enable the "persistent session" option for the account (see [how](https://user-images.githubusercontent.com/1560781/73009657-0a400780-3e22-11ea-9608-39329e999d27.png)) And then you just fill the login forms the same way you do in a browser. Then if you restart the app there will be no need to fill login forms again since the securely saved sessions will be reused.

**Comment by vladimiry** [comment]
The issue has been addressed, so got closed.

**Comment by joeschmoe1869** [comment]
Why did you close this topic?? The issue is NOT resolved. I cannot log into Electronmail to make the suggested changes. So How do I log in due to not getting a prompt for the 2FA???

**Comment by vladimiry** [comment]
The issue is closed because it has been addressed. Please read the above-provided responses with attention. Not working for you feature doesn't necessary mean that the feature is broken in the app.

**Comment by joeschmoe1869** [comment]
Yet, due to incorrect configuration of 2FA the app is not allowing access. I can access Proton Mail just fine. So there is a flaw in the app. This issue isn't resolved as access to Proton Mail is fine, access to the Electron Mail is not. Which reflects a flaw in  the app

**Comment by joeschmoe1869** [comment]
How can I access Electron mail to make your suggested changes?

**Comment by vladimiry** [comment]
> The app supports automatic generating and filling 2FA tokens. See this issue https://github.com/vladimiry/ElectronMail/issues/10 for details. So you enter in the app settings secret seed, not the one-time-token 6 digits token. So 6 digits token is supposed to be filled on the proton form, but not in the app settings.

> If you don't want to save the credentials in the app but still want automated login, enable the "persistent session" option for the account (see [how](https://user-images.githubusercontent.com/1560781/73009657-0a400780-3e22-11ea-9608-39329e999d27.png)) And then you just fill the login forms the same way you do in a browser, like manually. Then if you restart the app there will be no need to fill login forms again since the securely saved sessions will be reused. See the `persistent session` feature description [here](https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.0).

You have two options of how to make auto-login into the proton account work. So just take the option that suits you better. If it's still unclear, then I don't know how to help more at this time.

**Comment by vladimiry** [comment]
@joeschmoe1869, in general, if you don't completely understand what you are doing with 2FA secrets/tokens then better not to use the ElectronMail app. I admit that it's not for everyone, maybe too complicated setup, etc.

**Comment by joeschmoe1869** [comment]
@vladimiry I'm completely understand MFA. I do not for a living. However, if your app doesn't support proper key entry and decryption there is a flaw. I use MFA on multiple devices within my network and Electron Mail is the only one that has failed to fully authenticate with the MFA configuration. 
It's easy to blame the end user instead of troubleshooting your app. Keep the issue closed. I'll use the Proton Mails web interface as it functions 100% correctly with MFA.

**Comment by vladimiry** [comment]
> No, it presents the password field. I enter the password and then get the error message unable to decrypt

So you didn't even got to the 2FA filling form and stopped on the password filling form? If so then the only reason for that I could name right now is a wrong password used. Since you get to the 2FA form only after the password form got successfully submitted.
